### ISSUE TITLE
framesia not displaying correct figure of dollar on a post in profile

### ISSUE THREAD

**Issue by cckole** [Framesia/paperframe#2]
The first five posts you will see when you enter your profile displays the amount you've gotten in a post correctly but when you load more, all other posts has $0.00 it doesn't show the correct amount ....

see the video link.......
https://youtu.be/YAwX3FLc9Lc

**Comment by damaera** [comment]
okay, good catch:
this is happening because I only showing `pending_payout_value`  and i'm ignoring `total_payout_value`
i'll fix later
